config/routes.rb
Rails.application.routes.draw do
  
  root to: "homes#top"
  devise_for :users
  
  resources :books, only: [:new, :create, :index, :show, :edit, :destroy, :update]
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home/about' => 'homes#about',as: 'about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :books, dependent: :destroy
         
         has_one_attached :profile_image
         
         validates :name, uniqueness: true
         validates :name, length: { in: 2..20 }
         validates :introduction, length: { maximum: 50 }
         
     def get_profile_image(width, height)
      unless profile_image.attached?
        file_path = Rails.root.join('app/assets/images/no_image.jpeg')
        profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
      end
        profile_image.variant(resize_to_limit: [width, height]).processed
     end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:top, :about]
    
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def after_sign_in_path_for(resource)
    @user = current_user
    end 
    
    def after_sign_out_path_for(resource)
    root_path
    end

    
    protected
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    end 
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
    render :index
    end 
  end 

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
    
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    render :edit
    else
    redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
    else
    render :edit
    end 
  end 
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end 
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end 
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :baria_user ,only:[:edit,:update ]
   
  def create
      @user = User.new(user_params)
      @user = current_user.id
    if @user.save
      redirect_to user_path(@user.id)
    else
      @user = current_user
      render :index
    end  
  end
    
  def index
    @users = User.all
    @user = current_user
  end 
  
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
   @user = User.find(params[:id])
   if @user.update(user_params)
     flash[:notice] = "You have updated user successfully."
   redirect_to user_path(@user.id)
   else
    render :edit
   end
  end 
   
   private
   
   def user_params
     params.require(:user).permit(:name, :profile_image, :introduction)
   end 
   
   def baria_user
       if params[:id].to_i != current_user.id
           redirect_to user_path(current_user)
       end 
   end 
   
end
  
  
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= flash[:notice] %>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            
<h1>Editing Book</h1>
<% if @book.errors.any? %>
<%= @book.errors.count %>error prohibited this obj from being saved:
<ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<%= form_with model: @book do |f| %>

<div>Title</div>
<%= f.text_field :title %>

<div>Body</div>
<%= f.text_area :body %>
<div>
    <%= f.submit 'Update Book' %>
</div>

<span>
    <%= link_to 'Show',"/books/#{@book.id}" %>
    |
    <%= link_to 'Back',"/books" %>
</span>
<% end %>

        </div>
    </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<%= @book.errors.count %>error prohibited this obj from being saved:
<ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>


<!-- ユーザー詳細 -->
<main>
  <div class="container px-5 px-sm0">
    <div class="row">
      <div class="col-md-3">
       <h2>User info</h2>
       <%= image_tag @user.get_profile_image(100,100) %><br>
       <table class="table">
         <tbody>
           <tr></tr>
           <tr>name</tr>
           <tr><%= @user.name %></tr><br>
           <tr>introduction</tr>
           <tr><%= @user.introduction %></tr>
         </tbody>
       </table>

<!-- user編集 -->
<div class="row">
<%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary" do %>
<i class="fas fa-user-cog"></i>
<% end %>
</div>

<!--投稿フォーム-->
<h1>New book</h1>

<%= form_with model: Book.new do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Opinion</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book' %>
<% end %>
</div>

<!--投稿一覧-->
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
    <thead>
        <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
        <tr>
            <td><%= link_to user_path(book.user) do %><%= image_tag @user.get_profile_image(100,100) %><% end %></td>
            <td><%= link_to book.title,book_path(book.id) %></td>
            <td><%= book.body %></td>
            
        </tr>
       <% end %>
    </tbody>
</table>

    </div>
  </div>
 </div>
</main>

app/views/books/new.html.erb
<h1>Books#new　投稿</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<!-- ユーザー詳細 -->
<main>
  <div class="container px-5 px-sm0">
    <div class="row">
      <div class="col-md-3">
       <h2>User info</h2>
       
       <%= image_tag @user.get_profile_image(100,100) %><br>
       <table class="table">
         <tbody>
           <tr></tr>
           <tr>name</tr>
           <tr><%= @user.name %></tr><br>
           <tr>introduction</tr>
           <tr><%= @user.introduction %></tr>
         </tbody>
       </table>

<!-- user編集 -->
<div class="row">
<%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary" do %>
<i class="fas fa-user-cog"></i>
<% end %>
</div>

<!--投稿フォーム-->
<h1>New book</h1>

<% if @book.errors.any? %>
<%= @book.errors.count %>error prohibited this obj from being saved:
<ul>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>


<%= form_with model: Book.new do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Opinion</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book' %>
<% end %>
</div>

<div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
        <tbody>
            <tr>
                <td><%= link_to user_path(@user) do %><%= image_tag @user.get_profile_image(100,100) %><br><%= @user.name %><% end %></td>
                <td><%= link_to @book.title %></td>
                <td><%= @book.body %></td>
                <% if @book.user == current_user %>
                <td><%= link_to 'Edit',"/books/#{@book.id}/edit" %></td>
                <td><%= link_to "Destroy.", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" %></td>
                <% end %>
            </tr>
        </tbody>
    </table>
   </div>
  </div>
 </div>
</main>

app/views/homes/about.html.erb
<main>
      <div class="container">
        <div class="row">
          <div class="px-3 mx-auto">
            <h1>
              welcome to<i class="fas fa-book"></i>
              <strong>Bookers</strong>
               !
              </h1>
          </div>
        </div>
      </div>
</main>

app/views/homes/top.html.erb
<main>
      <div class="container">
        <div class="row">
          <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>
              welcome to<i class="fas fa-book"></i>
              <strong>Bookers</strong>
               !!
              </h1>
              <p>
                In <i class="fas fa-book"></i>
                <strong>Bookers</strong>
                , 
              </p>
              <p>you can share and exchange your opinions , inpressions , and emotions</p>
              <p> about various books!</p>
              <div class="bth-warpper col-10 mx-auto">
                  <div class="row">
                      <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
                  </div>
                  <div class="row">
                      <a class="btn btn-success btn-sm btn-block mb-3 sign_up" href="/users/sign_up">Sign up</a>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-bark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/">
            <span class="text-white">Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse"data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expande="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
      
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to user_path(current_user), class: 'nav-link text-white' do %>
        <i class="fas fa-home"></i>Home
        <% end %>
      </li>
      
      <li class="nav-item">
        <%= link_to users_path, class: 'nav-link text-white' do %>
        <i class="fas fa-users"></i>Users
        <% end %>
      </li>
      
      <li class="nav-item">
        <%= link_to books_path, class: 'nav-link text-white' do %>
         <i class="fas fa-book-open"></i>Books
         <% end %>
      </li>
      
      <li class="nav-item">
        <%= link_to destroy_user_session_path,method: :delete, class: 'nav-link text-white' do %>
        <i class="fas fa-sign-out-alt"></i>Log out
        <% end %>
      </li>
      
      <% else %>
       <li class="nav-item">
        <%= link_to root_path, class: 'nav-link text-white' do %>
        <i class="fas fa-home"></i>Home
        <% end %>
      </li>
      
      <li class="nav-item">
        <%= link_to about_path, class: 'nav-link text-white' do %>
        <i class="fas fa-link"></i>About
        <% end %>
      </li>
      
      <li class="nav-item">
        <%= link_to new_user_registration_path, class: 'nav-link text-white' do %>
        <i class="fas fa-user-plus"></i>Sign up
        <% end %>
      </li>
      
      <li class="nav-item">
        <%= link_to new_user_session_path, class: 'nav-link text-white' do %>
        <i class="fas fa-sign-in-alt"></i>Log in
        <% end %>
      </li>
      <% end %>
         </ul>
        </div>
       </div>
      </nav>
    </header>
    <% if flash[:notice] %>
    <div>
      <%= flash[:notice] %>
    </div>
    <% end %>
    <%= yield %>
  
    <footer>
        <div class="container mt-5">
          <div class="row">
            <div class="mx-auto">
                <p>CopyRight Infratop.inc</p>
            </div>
          </div>
        </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<main>
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
                <h2>User info</h2>
                
               <% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
                
                <%= form_with model: @user do |f| %>
                <label for="inputName">Name</label><br>
                <%= f.text_field :name, autofocus: true, id:"inputName" %><br>
                <label for="inputImage">Image</label><br>
                <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br>
                <label for="inputIntroduction">Introduction</label><br>
                <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction"%><br>
                <%= f.submit "Update User" %>
                <% end %>
            </div>
        </div>
    </div>
</main>

app/views/users/index.html.erb
<!-- ユーザー詳細 -->
<main>
  <div class="container px-5 px-sm0">
    <div class="row">
      <div class="col-md-3">
       <h2>User info</h2>
       <%= image_tag @user.get_profile_image(100,100) %><br>
       <table class="table">
         <tbody>
           <tr></tr>
           <tr>name</tr>
           <tr><%= @user.name %></tr><br>
           <tr>introduction</tr>
           <tr><%= @user.introduction %></tr>
         </tbody>
       </table>

<!-- user編集 -->
<div class="row">
<%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary" do %>
<i class="fas fa-user-cog"></i>
<% end %>
</div>

<!--投稿フォーム-->
<h1>New book</h1>

<%= form_with model: Book.new do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Opinion</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book' %>
<% end %>
</div>

<!--User 一覧 -->
<div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table">
        <thead>
            <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
            <tr>
                <td><%= link_to user_path(user) do %><%= image_tag user.get_profile_image(100,100) %><% end %></td>
                <td><%= user.name %></td>
                <td><%= link_to 'Show',user_path(user) %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/users/show.html.erb
<!-- ユーザー詳細 -->
<main>
  <div class="container px-5 px-sm0">
    <div class="row">
      <div class="col-md-3">
       <h2>User info</h2>
       <%= image_tag @user.get_profile_image(100,100) %><br>
       <table class="table">
         <tbody>
          <tr></tr>
           <tr>
           <th>name</th>
           <th><%= @user.name %></th><br>
           </tr>
           <tr>
           <th>introduction</th>
           <th><%= @user.introduction %></th>
           </tr>
         </tbody>
       </table>
<!-- user編集 -->
<div class="row">
<%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary" do %>
<i class="fas fa-user-cog"></i>
<% end %>
</div>

<!--投稿フォーム-->
<h1>New book</h1>


<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Opinion</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'Create Book' %>
<% end %>
</div>


<!--投稿一覧-->
<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-hover table-inverse">
    <thead>
        <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
        <tr>
            <td><%= link_to user_path(book.user) do %><%= image_tag @user.get_profile_image(100,100) %><% end %></td>
            <td><%= link_to book.title,book_path(book) %></td>
            <td><%= book.body %></td>
            
        </tr>
       <% end %>
    </tbody>
</table>

    </div>
  </div>
 </div>
</main>